----------------------------------------------
-- 01_tables_schema.sql                     --
-- ENG: Create empty tables. TYPE: HUF      --
-- HUN: Üres táblák létrehozása. TÍPUS: FT  --
----------------------------------------------
--  1.: Employees                           --
--  2.: Salary_log                          --
--  3.: Error_log.                          --
----------------------------------------------

SET SERVEROUTPUT ON;

CREATE TABLE employees(
    employee_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name            VARCHAR2(30),
    last_name             VARCHAR2(30),
    email                 VARCHAR2(100) UNIQUE,
    salary                NUMBER(10,0),
    department_id         NUMBER , 
        -- ENG: Later available for Foreign Key; the 'departments' table is not live yet.
        -- HUN: Későbbi Foreign Key helye; a 'departments' tábla még nem létezik.
    status                VARCHAR2(10) DEFAULT 'ACTIVE',
    CONSTRAINT chk_salary CHECK (salary > 250000),
    CONSTRAINT chk_status CHECK (status IN('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

BEGIN
DBMS_OUTPUT.PUT_LINE('HUN: Üres Employees tábla létrehozva!');
DBMS_OUTPUT.PUT_LINE('ENG: Empty Employees table created!');
END;

/

CREATE TABLE salary_log(
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id                NUMBER,
    old_salary                 NUMBER(10,0),
    new_salary                 NUMBER(10,0),
    change_date                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by                VARCHAR2(50),
    CONSTRAINT fk_log_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
    -- ENG: We connect the log to the employees. Only works with existing employees!
    -- HUN: Összekötjük a naplót az alkalmazottal. Csak létező alkalmazottal futhat le!
);

BEGIN
DBMS_OUTPUT.PUT_LINE('HUN: Üres salary_log tábla létrehozva!');
DBMS_OUTPUT.PUT_LINE('ENG: Empty salary_log table created!');
END;

/

CREATE TABLE error_log(
    error_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_type  VARCHAR2(100),
    message     VARCHAR2(500),
    emp_id      NUMBER,
    created_by  VARCHAR2(50) DEFAULT USER,
    create_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

BEGIN
DBMS_OUTPUT.PUT_LINE('HUN: Üres error_log tábla létrehozva!');
DBMS_OUTPUT.PUT_LINE('ENG: Empty error_log table created!');
END;

/